In [1]:
def my_function():
    print("Hello from a function")


In [2]:
my_function()

Hello from a function


In [9]:
def person(fname):
    print(fname+" Trump")

In [10]:
person("Donald")

Donald Trump


In [13]:
def add(a,b):
    return a+b,a
    


In [12]:
add(2,4)

6

In [15]:
def swap(a,b):
    a,b=b,a
    print(a)
    print(b)
    

In [16]:
swap(3,8)



8
3


In [27]:
def swap(a):
   return a%10
    

In [29]:
swap(20)

0

In [ ]:
def swap(a,b):
    

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [5]:
arr1=np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])


In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
print(arr1.ndim)

1


In [14]:
arr3=np.array(55)


In [15]:
arr3

array(55)

In [16]:
#Oth dimension
print(arr3.ndim)

0


In [17]:
#creating an array of zeros
arr4=np.zeros((2,3))


In [18]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
arr5=np.ones((3,3))

In [20]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
print(arr5.ndim)

2


In [22]:
type(arr5)

numpy.ndarray

In [23]:
print(arr4.ndim)


2


In [26]:
arr6=np.array([[1,2,3],[4,5,6]])


In [27]:
arr6


array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr6[0,1]

np.int64(2)

In [34]:
arr7=np.array([1,2,3,4,5])

In [35]:
arr7

array([1, 2, 3, 4, 5])

In [36]:
#Slicing can be complex for matrix so ignore it
arr8=np.array([[1,2,3],[4,5,6]])

In [37]:
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
print(arr8[1:5])

[[4 5 6]]


In [42]:
print(arr8[2:4])

[]


In [43]:
#Vectors slicing/ranging 
#also do negative indexing
arr9=np.array([1,2,3,4,5])

In [44]:
arr9

array([1, 2, 3, 4, 5])

In [45]:
print(arr9[1:5])

[2 3 4 5]


In [46]:
print(arr9[2:8])

[3 4 5]


In [49]:
print(arr9[4:])

[5]


In [50]:
print(arr9[ :6])

[1 2 3 4 5]


In [51]:
arr9=np.array([1,2,3,4,5])


In [52]:
arr9

array([1, 2, 3, 4, 5])

In [53]:
#step range
print(arr9[1:5:2])

[2 4]


In [54]:
arr8=np.array([[1,2,3],[4,5,6]])


In [55]:
#giving the rows and the values
print(arr8.shape)

(2, 3)


In [57]:
#converting 1-d to 2-d
arr9=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr9.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
#converting 1-d to 3-d
newarr=arr9.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [59]:
print(newarr.ndim)

3


In [3]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [4]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [5]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [6]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [7]:
#Row 
arr1=np.array([[4,5],[6,7]])
arr2=np.array([[8,9],[10,11]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 4  5  8  9]
 [ 6  7 10 11]]


In [9]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)
      

[array([1, 2]), array([3, 4]), array([5, 6])]


In [10]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)
      

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [11]:
from numpy import random
x=random.randint(100)
print(x)


38


In [12]:
#Float value will come from 0 to 1 randomly
from numpy import random
x=random.rand()
print(x)

0.07564584202295788


In [13]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[31 61 46 57 39]


In [14]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[ 7 15 70 45  6]
 [77 42 65 15 30]
 [66 31 95 33  6]]


In [15]:
from numpy import random
x=random.rand(5)
print(x)

[0.21486904 0.8316576  0.55291848 0.85542326 0.01364169]


In [16]:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.44964951 0.23899691 0.74231086 0.04647464 0.74361669]
 [0.16561362 0.06241447 0.09722061 0.07325816 0.7788337 ]
 [0.1684154  0.40538282 0.1129376  0.62387625 0.86671136]]


In [2]:
#only on elist will be updated
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
#both list will be updated
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#transpose=changes row to column

In [5]:
arr_str=['Mercedes','BMW','Audi','Ferrari','Tesla']
arr_num=[5,4,6,7,3]


In [6]:
np_arr_str=np.array(arr_str)
np_arr_num=np.array(arr_num)
print('Numpy Array (arr_str): ',np_arr_str)
print('Numpy Array (arr_num): ',np_arr_num)

Numpy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num):  [5 4 6 7 3]


In [7]:
print('Data type of arr_str: ',type(arr_str))
print('Data type of arr_num: ',type(arr_num))
print('Data type of np_arr_str: ',type(np_arr_str))
print('Data type of np_arr_num: ',type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


In [8]:
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [9]:
print('Data type of matrix: ',type(matrix))

Data type of matrix:  <class 'numpy.ndarray'>


In [13]:
arr2  = np.arange(start = 0, stop = 10) # 10 will be excluded from the output
print(arr2)

# or

arr2  = np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
# adding a step size of 5 to create an array
arr3  = np.arange(start = 0, stop = 20, step = 5)
print(arr3)

[ 0  5 10 15]


In [16]:
matrix2 = np.linspace(0,5) # by default 50 evenly spaced values will be generated between 0 and 5
print(matrix2)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
